config/routes.rb
Wheretolearn::Application.routes.draw do

=begin
  get "users/index"

  get "users/edit"

  get "users/update"

  get "users/new"

  get "users/create"

  get "users/destroy"

  get "roles/index"

  get "roles/edit"

  get "roles/update"

  get "roles/new"

  get "roles/create"

  get "roles/destroy"

  get "role/index"

  get "role/edit"

  get "role/update"

  get "role/new"

  get "role/create"

  get "role/destroy"
=end

  get "search/search"

  resources :schedtypes

  resources :costtypes

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    :roles
  end

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :usedmethods

  resources :deliverymethods

  resources :sourcetypes

  resources :category1s do
    resources :category2s do
      resources :category3s
    end 
  end

  

  resources :portfolios do
    resources :opinions
  end

  resources :sources do
    resources :contenttags
    resources :portfolios
    resources :opinions
  end

  resources :subjects do
    resources :subject_modules do
      resources :contenttags
      resources :portfolios
    end
    resources :contenttags

  end

match  ':controller/:action.:format'

  root :to => 'search#search'

  mount Blogit::Engine => '/blog'

  get 'subject_tags/:tag', to: 'subjects#index', as: :subject_tag
  get 'source_tags/:tag', to: 'sources#index', as: :source_tag

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/deliverymethod.rb
class Deliverymethod < ActiveRecord::Base
  attr_accessible :dmcod, :dmdesc, :dmimgh, :dmimgtype, :dmimgurl, :dmimgw

  has_many :usedmethods, :inverse_of => :deliverymethod
  has_many :portfolios, :through => :usedmethods

  resourcify
end

app/controllers/deliverymethods_controller.rb
class DeliverymethodsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  load_and_authorize_resource
  # GET /deliverymethods
  # GET /deliverymethods.json
  def index
    @deliverymethods = Deliverymethod.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deliverymethods }
    end
  end

  # GET /deliverymethods/1
  # GET /deliverymethods/1.json
  def show
    @deliverymethod = Deliverymethod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deliverymethod }
    end
  end

  # GET /deliverymethods/new
  # GET /deliverymethods/new.json
  def new
    @deliverymethod = Deliverymethod.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deliverymethod }
    end
  end

  # GET /deliverymethods/1/edit
  def edit
    @deliverymethod = Deliverymethod.find(params[:id])
  end

  # POST /deliverymethods
  # POST /deliverymethods.json
  def create
    @deliverymethod = Deliverymethod.new(params[:deliverymethod])

    respond_to do |format|
      if @deliverymethod.save
        format.html { redirect_to @deliverymethod, notice: 'Deliverymethod was successfully created.' }
        format.json { render json: @deliverymethod, status: :created, location: @deliverymethod }
      else
        format.html { render action: "new" }
        format.json { render json: @deliverymethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deliverymethods/1
  # PUT /deliverymethods/1.json
  def update
    @deliverymethod = Deliverymethod.find(params[:id])

    respond_to do |format|
      if @deliverymethod.update_attributes(params[:deliverymethod])
        format.html { redirect_to @deliverymethod, notice: 'Deliverymethod was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deliverymethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliverymethods/1
  # DELETE /deliverymethods/1.json
  def destroy
    @deliverymethod = Deliverymethod.find(params[:id])
    @deliverymethod.destroy

    respond_to do |format|
      format.html { redirect_to deliverymethods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/deliverymethods_helper.rb
module DeliverymethodsHelper
end

app/views/deliverymethods/_form.html.erb
<%= form_for(@deliverymethod) do |f| %>
  <% if @deliverymethod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deliverymethod.errors.count, "error") %> prohibited this deliverymethod from being saved:</h2>

      <ul>
      <% @deliverymethod.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dmcod %><br />
    <%= f.text_field :dmcod %>
  </div>
  <div class="field">
    <%= f.label :dmdesc %><br />
    <%= f.text_field :dmdesc %>
  </div>
  <div class="field">
    <%= f.label :dmimgurl %><br />
    <%= f.text_field :dmimgurl %>
  </div>
  <div class="field">
    <%= f.label :dmimgtype %><br />
    <%= f.text_field :dmimgtype %>
  </div>
  <div class="field">
    <%= f.label :dmimgw %><br />
    <%= f.number_field :dmimgw %>
  </div>
  <div class="field">
    <%= f.label :dmimgh %><br />
    <%= f.number_field :dmimgh %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deliverymethods/edit.html.erb
<h1>Editing deliverymethod</h1>

<%= render 'form' %>

<%= link_to 'Show', @deliverymethod %> |
<%= link_to 'Back', deliverymethods_path %>

app/views/deliverymethods/index.html.erb
<h1>Listing deliverymethods</h1>

<table>
  <tr>
    <th>Dmcod</th>
    <th>Dmdesc</th>
    <th>Dmimgurl</th>
    <th>Dmimgtype</th>
    <th>Dmimgw</th>
    <th>Dmimgh</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deliverymethods.each do |deliverymethod| %>
  <tr>
    <td><%= deliverymethod.dmcod %></td>
    <td><%= deliverymethod.dmdesc %></td>
    <td><%= deliverymethod.dmimgurl %></td>
    <td><%= deliverymethod.dmimgtype %></td>
    <td><%= deliverymethod.dmimgw %></td>
    <td><%= deliverymethod.dmimgh %></td>
    <td><%= link_to 'Show', deliverymethod %></td>
    <td><%= link_to 'Edit', edit_deliverymethod_path(deliverymethod) %></td>
    <td><%= link_to 'Destroy', deliverymethod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deliverymethod', new_deliverymethod_path %>

app/views/deliverymethods/new.html.erb
<h1>New deliverymethod</h1>

<%= render 'form' %>

<%= link_to 'Back', deliverymethods_path %>

app/views/deliverymethods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dmcod:</b>
  <%= @deliverymethod.dmcod %>
</p>

<p>
  <b>Dmdesc:</b>
  <%= @deliverymethod.dmdesc %>
</p>

<p>
  <b>Dmimgurl:</b>
  <%= @deliverymethod.dmimgurl %>
</p>

<p>
  <b>Dmimgtype:</b>
  <%= @deliverymethod.dmimgtype %>
</p>

<p>
  <b>Dmimgw:</b>
  <%= @deliverymethod.dmimgw %>
</p>

<p>
  <b>Dmimgh:</b>
  <%= @deliverymethod.dmimgh %>
</p>


<%= link_to 'Edit', edit_deliverymethod_path(@deliverymethod) %> |
<%= link_to 'Back', deliverymethods_path %>