config/routes.rb
Wheretolearn::Application.routes.draw do

=begin
  get "users/index"

  get "users/edit"

  get "users/update"

  get "users/new"

  get "users/create"

  get "users/destroy"

  get "roles/index"

  get "roles/edit"

  get "roles/update"

  get "roles/new"

  get "roles/create"

  get "roles/destroy"

  get "role/index"

  get "role/edit"

  get "role/update"

  get "role/new"

  get "role/create"

  get "role/destroy"
=end

  get "search/search"

  resources :schedtypes

  resources :costtypes

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    :roles
  end

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :usedmethods

  resources :deliverymethods

  resources :sourcetypes

  resources :category1s do
    resources :category2s do
      resources :category3s
    end 
  end

  

  resources :portfolios do
    resources :opinions
  end

  resources :sources do
    resources :contenttags
    resources :portfolios
    resources :opinions
  end

  resources :subjects do
    resources :subject_modules do
      resources :contenttags
      resources :portfolios
    end
    resources :contenttags

  end

match  ':controller/:action.:format'

  root :to => 'search#search'

  mount Blogit::Engine => '/blog'

  get 'subject_tags/:tag', to: 'subjects#index', as: :subject_tag
  get 'source_tags/:tag', to: 'sources#index', as: :source_tag

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  attr_accessible :cost, :currency, :enddate, :physaddress,
                  :pweburl, :schedtype_id, :source_id, :startdate, :subject_id, :subject_module_id, :costtype_id, :slug,
                  :prttitle, :prtdesc, :prttrial, :prttiercost

  belongs_to :source, :inverse_of => :portfolios
    delegate :srcname, :to => :source
  belongs_to :subject_module, :inverse_of => :portfolios
    delegate :smname, :smdesc, :to => :subject_module
  belongs_to :subject, :inverse_of => :portfolios
    delegate :subname, :to => :subject
  belongs_to :costtype, :inverse_of => :portfolios
    delegate :costname, :to => :costtype
  belongs_to :schedtype, :inverse_of => :portfolios
    delegate :schedname, :to => :schedtype
  has_many :usedmethods, :as => :deliverable
  has_many :deliverymethods, :through => :usedmethods
    delegate :dmdesc, :to => :deliverymethods
  has_many :opinions, :as => :opinionable



  belongs_to :created_by, class_name: 'User' #, :inverse_of => :portfolios
  belongs_to :updated_by, class_name: 'User' #, :inverse_of => :portfolios

  def updater(user)
    self.updated_by_id = user.id
    self.save
  end

def folioname
  srcname.to_s + " - " + subname.to_s + " : " + smname.to_s
end

def ttlname
  srcname.to_s + " - " + subname.to_s
end

  def srchtitle
    folioname
  end

  def pagetitle
    subname.to_s + " portfolio from " + srcname.to_s
  end

  def clstype
    "Portfolio"
  end

  def srchparent
    self.source
  end

  def srchtext
    prtdesc
  end


  #belongs_to :subject, :through => :subject_module
  #, :inverse_of => :portfolios
  attr_accessible :usedmethods_attributes

  accepts_nested_attributes_for :usedmethods , :reject_if => lambda { |a| a[:deliverymethod_id].blank? }, :allow_destroy => true

  validates_associated :usedmethods

  validates :prttitle,
            :presence => true,
            :uniqueness => false,

            :length => { :maximum => 50, :minimum => 3 }

  validates :prtdesc,
            :presence => false,

            :length => { :maximum => 1000, :minimum => 3 }



  extend FriendlyId
  friendly_id :folioname, use: :slugged
  #TODO: Need to decide whether to keep folioname based on source - subject : module or use title and desc

  include PgSearch
  multisearchable :against => [:cost, :currency, :enddate, :physaddress, :pweburl, :startdate, :prttitle, :prtdesc]
  pg_search_scope :search_by_basic, :against => [:cost, :currency, :enddate, :physaddress,:pweburl, :startdate, :prttitle, :prtdesc],
                  :associated_against => {:source => :name, :subject => :name, :subject_module => :smname, :opinions => [:optitle,:comment,:rating]
                  }


  resourcify

  #TODO: Configure rating to not require decimals
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  load_and_authorize_resource
  # GET /portfolios
  # GET /portfolios.json

  def index


    #if params[:tag]
    #  #@sources = Source.tagged_with(params[:tag])
    #  @portfolios = Portfolio.all
    if params[:srchquery]
      @portfolios = Portfolio.search_by_basic(params[:srchquery])
      #@portfolios = Portfolio.search_by_link(params[:srchquery])
    else
      @portfolios = Portfolio.all
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @portfolios }
    end
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/new
  # GET /portfolios/new.json
  def new
    @portfolio = Portfolio.new
    @portfolio.usedmethods.build
    #@portfolio.usedmethods.deliverymethods.build
    @subjects = Subject.find(:all,:order => "name")
    @subject_modules = SubjectModule.find(:all, :order => "smname")

    @deliverymethods = Deliverymethod.find(:all,:order => "dmcod")
    @selected_subject = @subjects[0]
    @currlist = view_context.currencylist
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/1/edit
  def edit
    @portfolio = Portfolio.find(params[:id])
    @portfolio.usedmethods.build
    @subjects = Subject.find(:all,:order => "name")
    @subject_modules = SubjectModule.find(:all, :order => "smname")

    @deliverymethods = Deliverymethod.find(:all,:order => "dmcod")
    @selected_subject = @portfolio.subject_module.subject
    @currlist = view_context.currencylist
    @usedmethods = @portfolio.usedmethods
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = current_user.portfolios.new(params[:portfolio])


    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render json: @portfolio, status: :created, location: @portfolio }
      else
        format.html { render action: "new" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end



  # PUT /portfolios/1
  # PUT /portfolios/1.json
  def update
    @portfolio = Portfolio.find(params[:id])


    respond_to do |format|
      if @portfolio.update_attributes(params[:portfolio])

        #if @portfolio.save
        if  @portfolio.updater current_user
          format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @portfolio.errors, status: :unprocessable_entity }

        end
      else
        format.html { render action: "edit" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

  def currencylist

    #@currencylist = { 0 => "CAD", 1 => "EUR", 2 => "GBP", 3 => "JMD", 4 => "USD"}
    @currencylist = { "CAD" => 0, "EUR" => 1, "GBP" => 2, "JMD" => 3, "USD" => 4}
    #@currencylist = [ "CAD", "EUR", "GBP", "JMD", "USD"]
  end





end

app/views/portfolios/_form.html.erb
<%= form_for (@portfolio), :html => { :class => 'form-horizontal' } do |f| %>

    <div class="control-group">
      <%= f.label 'Title:', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :prttitle, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label 'Description:', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :prtdesc, :rows => 3, :class => 'text_area' %>
      </div>
    </div>

  <div class="control-group">
    <%= f.label 'Source', :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :source_id, Source.find(:all), :id, :name, :prompt => "Select a Source", :class => 'dropdown_field'  %>
    </div>
  </div>

    <div class="control-group">
      <%= f.label 'Subject & Module', :class => 'control-label' %>
      <div class="controls">

        <%= f.collection_select :subject_id, @subjects, :id, :name, :prompt => "Select a Subject", :class => 'dropdown_field' %>
        <%= f.collection_select :subject_module_id, @subject_modules, :id, :smname, :prompt => "Select a Module", :class => 'dropdown_field' %>
      </div>
    </div>

  <div class="control-group">
    <%= f.label 'Web URL:', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pweburl, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Physical Address:', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :physaddress, :rows => 3, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Cost', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cost, size: 15, :class => 'text_field' %>
      <%= f.select :currency, @currlist.map{|cl| [ cl[0], cl[0] ]},:prompt => "Select a Currency", :class => 'dropdown_field' %>
    </div>
  </div>

    <div class="control-group">
      <%= f.label 'Cost Type:', :class => 'control-label' %>
      <div class="controls">

        <%= f.collection_select :costtype_id, Costtype.find(:all), :id, :costname, :prompt => "Select a Type", :class => 'dropdown_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label 'Tiered Costs:', :class => 'control-label' %>
      <div class="controls">
        <%=hidden_field_tag 'portfolio[prttiercost]', '0'%>
        <%=check_box_tag 'portfolio[prttiercost]', 1, @portfolio.prttiercost %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label 'Free Trial:', :class => 'control-label' %>
      <div class="controls">
        <%=hidden_field_tag 'portfolio[prttrial]', '0'%>
        <%=check_box_tag 'portfolio[prttrial]', 1, @portfolio.prttrial %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :schedtype_id, :class => 'control-label' %>
      <div class="controls">

        <%= f.collection_select :schedtype_id, Schedtype.find(:all), :id, :schedname, :prompt => "Select a Type", :class => 'dropdown_field' %>
      </div>
    </div>


    <div class="control-group">
    <%= f.label :startdate, :class => 'control-label' %>
    <div class="controls">

      <%= f.text_field :startdate, :class => 'datepicker', :size => 10, :maxlength => 10 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :enddate, :class => 'control-label' %>
    <div class="controls">

      <%= f.text_field :enddate, :class => 'datepicker', :size => 10, :maxlength => 10 %>
    </div>
  </div>
    <p></p><p></p>

    <fieldset>
      <legend>Delivery Methods <%= "for #{ @portfolio.source.name + @portfolio.subject_module.subjtitle }" unless @portfolio.source.blank? %></legend>
      <div  id="usedmethods">
        <table width="200" id="usedmethods-table" class="table table-hover table-striped" >
          <thead>
          <th></th>

          <th></th>
          </thead>
          <tbody>

          <tr><td><p><%= link_to_add_fields2( "Add a Method", f, :usedmethods,:class => "btn btn-primary") %></p></td><td></td></tr>
          <%= render('usedmethod_fields', :f => f) %>
          </tbody>
        </table>
        <p></p>
      </div>
    </fieldset>


  <div class="form-actions">
    <%= f.submit "Save", :class => 'btn btn-primary', :title => "Save the changes to this Portfolio." %>

    <%= link_to( t('.cancel', :default => t("helpers.links.cancel")), portfolios_path, :confirm => "Are you sure you want to cancel?  Any changes will be lost.", :class => "btn", :title => "Cancel the changes and return to the Portfolio Index.") %>
  </div>
<% end %>

app/views/portfolios/_portfolioindexgrid.html.erb
<div id="masonry-container" class="transitions-enabled infinite-scroll  clearfix">
  <% @portfolios.each do |portfolio| %>

      <div class="boxd3 col2" >

        <h4><%= link_to portfolio.prttitle, portfolio,:class => "gridlink" %></h4>
        <p><strong>Description</strong>: <%= truncate(portfolio.prtdesc, length: 100) %></p>
        <p><strong>Subject</strong>: <%= portfolio.subject_module.subjtitle  %></p>
        <p><strong>Source</strong>: <%= portfolio.source.name  %></p>


        <p>
        <%= link_to glyph('info-sign'), portfolio %>
        <%= link_to glyph(:edit), edit_portfolio_path(portfolio) %>
        <%= link_to glyph(:remove), portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></p>


      </div>
  <% end %>
</div>

<br>

app/views/portfolios/_portfolioindextable.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Desc</th>
    <th>Subject & Module</th>
    <th>Source</th>

    <th>Cost</th>

    <th>Schedule Type</th>

    <th>Start Date</th>
    <th>End Date</th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= link_to portfolio.prttitle , portfolio_path(portfolio), :class => "tablelink"  %></td>

        <td><%= truncate(portfolio.prtdesc, length: 100) %></td>

        <td><%= portfolio.subject_module.subjtitle %></td>
        <td><%= portfolio.source.name %></td>


        <td><%= portfolio.cost %> <%= portfolio.currency %><br><%= portfolio.costtype.costname %></td>

        <td><%= portfolio.schedtype.schedname %></td>

        <td><%=  listdt(portfolio.startdate) %></td>
        <td><%=  listdt(portfolio.enddate) %></td>

        <td>
          <%= link_to 'Show', portfolio, :class => 'btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_portfolio_path(portfolio), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      portfolio_path(portfolio),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/portfolios/_usedmethod_display.html.erb
<table id="subject_modules-display-table" class="table table-hover table-striped">
  <thead>
      <th>Name</th>
      <th>Description</th>

  </thead>
  <tbody>

      <% @portfolio.usedmethods.each do |usedmethods| %>
          <tr class="fields">
            <td><%= usedmethods.deliverymethod.dmcod %></td>
            <td><%= usedmethods.deliverymethod.dmdesc %></td>

          </tr>
      <% end %>
  </tbody>
</table>

app/views/portfolios/_usedmethod_fields.html.erb
<%= f.fields_for(:usedmethods) do |usedmethods_form| %>
<tr class="fields">
  <td>
        <%= usedmethods_form.collection_select( :deliverymethod_id, @deliverymethods, :id, :dmdesc, options ={:prompt => "Select a Method"}) %>

    <%= usedmethods_form.hidden_field(:_destroy, :class => "field") %>

  </td>

  <% if current_page?(new_portfolio_path) || current_page?(edit_portfolio_path) %>
      <td>

        <%= link_to_remove_fields('<b class="icon-remove"></b>'.html_safe, usedmethods_form, :title => "Delete this Method.") %>
      </td>
  <% end %>



</tr>

<% end %>

app/views/portfolios/_usedmethod_fields_modalversion.html.erb
<div id="new-usedmethod-fields" class="modal fade" data-backdrop="static">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Add a Method<%= " to the #{ @portfolio.source.name } Portfolio" unless @portfolio.source.nil? %></h3>
  </div>
  <div class="modal-body">
    <fieldset>

      <div class="control-group">
        <%= f.label(:dmcod, :class => "control-label") %>
        <div class="controls">
          <%= collection_select(:deliverymethod, :id, @deliverymethods, :id, :dmcod, options ={:prompt => "Select a Method"}, :class =>"deliverymethod") %>

        </div>
      </div>



      <%= f.hidden_field(:_destroy, :class => "field") %>
    </fieldset>
  </div>
  <div class="modal-footer">
    <button id="addButton" type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true" title="Add this method to the list of methods that are assigned to this portfolio.">Add</button>
    <button id="cancelButton" type="button" class="btn btn-inverse" data-dismiss="modal" aria-hidden="true" title="Close this screen without adding the method to the list.">Cancel</button>
  </div>
</div>

<script type="text/javascript">
  //usedmethodFieldsUI.init();
</script>

app/views/portfolios/_usedmethod_table.html.erb
<table id="usedmethods-table" class="table table-hover table-striped">
  <thead>
    <th>Delivery Method</th>

  <th></th>
  </thead>
  <tbody>
    <%= f.fields_for(:usedmethods) do |usedmethods_form| %>
      <tr class="fields">
        <td>
          <%= collection_select(:deliverymethod, :id, @deliverymethods, :id, :dmcod, options ={:prompt => "Select a Method"}, :class =>"deliverymethod") %>
        </td>

        <% if current_page?(new_portfolio_path) || current_page?(edit_portfolio_path) %>
            <td>
              <%= link_to_remove_fields('<b class="icon-remove">x</b>'.html_safe, usedmethods_form, :title => "Delete this Method.") %>
            </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/portfolios/edit.html.erb
<%- model_class = Portfolio -%>
<% title 'Make changes to the ' + @portfolio.pagetitle %>

<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/portfolios/index.html.erb
<% title "Browse our Portfolios" %>
<%- model_class = Portfolio -%>

<div class="row">
  <div class="page-header col-md-12">
    <h1><span style="border-right:1px #F5D15F solid;margin-right: 10px">Portfolios </span><%= link_to 'Create One', new_portfolio_path, class: "btn btn-mini btn-success" %>
      <%= render partial: 'search/searchmodel', locals: {:clearpath => portfolios_path} %>
    </h1>
  </div>
</div>

<div id="divgrid">
  <%= render partial: 'portfolioindexgrid' %>
</div>
<div id="divlist">
  <%= render partial: 'portfolioindextable' %>
</div>

app/views/portfolios/new.html.erb
<%- model_class = Portfolio -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/portfolios/show.html.erb
<%- model_class = Portfolio -%>
<% title 'Find out more about the ' + @portfolio.pagetitle %>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %>: <%= @portfolio.prttitle %>, from <%= @portfolio.source.name %></h1>
</div>

<div class=row">
  <div class="col-md-5">
    <dl class="dl-horizontal">


      <dt><strong>Subject & Module:</strong></dt>
      <dd><%= @portfolio.subject_module.subjtitle %></dd>
      <dt><strong>Description:</strong></dt>
      <dd><%= @portfolio.prtdesc %></dd>
      <dt><strong>Web Url:</strong></dt>
      <dd><%= link_to truncate(@portfolio.pweburl, :length => 40), readdhttp(@portfolio.pweburl), :class => "tablelink", :target => "_blank" %></dd>
      <dt><strong>Address:</strong></dt>
      <dd><%= @portfolio.physaddress %></dd>
    </dl>
  </div>

  <div class="col-md-7">
    <dl class="dl-horizontal">
      <dt><strong>Cost:</strong></dt>
      <dd><%= @portfolio.cost %></dd>
      <dt><strong>Currency:</strong></dt>
      <dd><%= @portfolio.currency %></dd>
      <dt><strong>Cost Type:</strong></dt>
      <dd><%= @portfolio.costtype.costname %></dd>
      <dt><strong>Tiered Cost:</strong></dt>
      <dd><%= boolyesno(@portfolio.prttiercost) %></dd>
      <dt><strong>Free Trial:</strong></dt>
      <dd><%= boolyesno(@portfolio.prttrial) %></dd>


      <dt><strong>Schedule Type:</strong></dt>
      <dd><%= @portfolio.schedtype.schedname %></dd>
      <dt><strong>Start Date:</strong></dt>
      <dd><%= longdttm(@portfolio.startdate) %></dd>
      <dt><strong>End Date:</strong></dt>
      <dd><%= longdttm(@portfolio.enddate) %></dd>


    </dl>
  </div>

</div><br><br>
<div class="row">
  <div class="col-md-5">
    <dt><strong>Used Methods:</strong></dt>
    <dd>
      <div class="well well-sm">
        <% @portfolio.usedmethods.each do |um| %>
            <span class="label label-default"><%= um.deliverymethod.dmdesc %></span>
        <% end %>
      </div>
    </dd>


  </div>
  <div class="col-md-7"></div>
</div>



<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              portfolios_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_portfolio_path(@portfolio), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              portfolio_path(@portfolio),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>