config/routes.rb
Wheretolearn::Application.routes.draw do

=begin
  get "users/index"

  get "users/edit"

  get "users/update"

  get "users/new"

  get "users/create"

  get "users/destroy"

  get "roles/index"

  get "roles/edit"

  get "roles/update"

  get "roles/new"

  get "roles/create"

  get "roles/destroy"

  get "role/index"

  get "role/edit"

  get "role/update"

  get "role/new"

  get "role/create"

  get "role/destroy"
=end

  get "search/search"

  resources :schedtypes

  resources :costtypes

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    :roles
  end

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :usedmethods

  resources :deliverymethods

  resources :sourcetypes

  resources :category1s do
    resources :category2s do
      resources :category3s
    end 
  end

  

  resources :portfolios do
    resources :opinions
  end

  resources :sources do
    resources :contenttags
    resources :portfolios
    resources :opinions
  end

  resources :subjects do
    resources :subject_modules do
      resources :contenttags
      resources :portfolios
    end
    resources :contenttags

  end

match  ':controller/:action.:format'

  root :to => 'search#search'

  mount Blogit::Engine => '/blog'

  get 'subject_tags/:tag', to: 'subjects#index', as: :subject_tag
  get 'source_tags/:tag', to: 'sources#index', as: :source_tag

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/usedmethod.rb
class Usedmethod < ActiveRecord::Base
  belongs_to :deliverymethod, :inverse_of => :usedmethods
  belongs_to :deliverable, :polymorphic => true

   attr_accessible :deliverymethod_id

  validates_uniqueness_of :deliverymethod_id, scope: [:deliverable_id, :deliverable_type]

  resourcify
end

app/controllers/usedmethods_controller.rb
class UsedmethodsController < ApplicationController
  load_and_authorize_resource
  
  # GET /usedmethods
  # GET /usedmethods.json
  def index
    @usedmethods = Usedmethod.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usedmethods }
    end
  end

  # GET /usedmethods/1
  # GET /usedmethods/1.json
  def show
    @usedmethod = Usedmethod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usedmethod }
    end
  end

  # GET /usedmethods/new
  # GET /usedmethods/new.json
  def new
    @usedmethod = Usedmethod.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usedmethod }
    end
  end

  # GET /usedmethods/1/edit
  def edit
    @usedmethod = Usedmethod.find(params[:id])
  end

  # POST /usedmethods
  # POST /usedmethods.json
  def create
    @usedmethod = Usedmethod.new(params[:usedmethod])

    respond_to do |format|
      if @usedmethod.save
        format.html { redirect_to @usedmethod, notice: 'Usedmethod was successfully created.' }
        format.json { render json: @usedmethod, status: :created, location: @usedmethod }
      else
        format.html { render action: "new" }
        format.json { render json: @usedmethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usedmethods/1
  # PUT /usedmethods/1.json
  def update
    @usedmethod = Usedmethod.find(params[:id])

    respond_to do |format|
      if @usedmethod.update_attributes(params[:usedmethod])
        format.html { redirect_to @usedmethod, notice: 'Usedmethod was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usedmethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usedmethods/1
  # DELETE /usedmethods/1.json
  def destroy
    @usedmethod = Usedmethod.find(params[:id])
    @usedmethod.destroy

    respond_to do |format|
      format.html { redirect_to usedmethods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/usedmethods_helper.rb
module UsedmethodsHelper
end

app/views/usedmethods/_form.html.erb
<%= form_for(@usedmethod) do |f| %>
  <% if @usedmethod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usedmethod.errors.count, "error") %> prohibited this usedmethod from being saved:</h2>

      <ul>
      <% @usedmethod.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deliverymethod %><br />
    <%= f.text_field :deliverymethod %>
  </div>
  <div class="field">
    <%= f.label :deliverable %><br />
    <%= f.text_field :deliverable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usedmethods/edit.html.erb
<h1>Editing usedmethod</h1>

<%= render 'form' %>

<%= link_to 'Show', @usedmethod %> |
<%= link_to 'Back', usedmethods_path %>

app/views/usedmethods/index.html.erb
<h1>Listing usedmethods</h1>

<table>
  <tr>
    <th>Deliverymethod</th>
    <th>Deliverable</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usedmethods.each do |usedmethod| %>
  <tr>
    <td><%= usedmethod.deliverymethod %></td>
    <td><%= usedmethod.deliverable %></td>
    <td><%= link_to 'Show', usedmethod %></td>
    <td><%= link_to 'Edit', edit_usedmethod_path(usedmethod) %></td>
    <td><%= link_to 'Destroy', usedmethod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usedmethod', new_usedmethod_path %>

app/views/usedmethods/new.html.erb
<h1>New usedmethod</h1>

<%= render 'form' %>

<%= link_to 'Back', usedmethods_path %>

app/views/usedmethods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Deliverymethod:</b>
  <%= @usedmethod.deliverymethod %>
</p>

<p>
  <b>Deliverable:</b>
  <%= @usedmethod.deliverable %>
</p>


<%= link_to 'Edit', edit_usedmethod_path(@usedmethod) %> |
<%= link_to 'Back', usedmethods_path %>