config/routes.rb
Wheretolearn::Application.routes.draw do

=begin
  get "users/index"

  get "users/edit"

  get "users/update"

  get "users/new"

  get "users/create"

  get "users/destroy"

  get "roles/index"

  get "roles/edit"

  get "roles/update"

  get "roles/new"

  get "roles/create"

  get "roles/destroy"

  get "role/index"

  get "role/edit"

  get "role/update"

  get "role/new"

  get "role/create"

  get "role/destroy"
=end

  get "search/search"

  resources :schedtypes

  resources :costtypes

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    :roles
  end

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :usedmethods

  resources :deliverymethods

  resources :sourcetypes

  resources :category1s do
    resources :category2s do
      resources :category3s
    end 
  end

  

  resources :portfolios do
    resources :opinions
  end

  resources :sources do
    resources :contenttags
    resources :portfolios
    resources :opinions
  end

  resources :subjects do
    resources :subject_modules do
      resources :contenttags
      resources :portfolios
    end
    resources :contenttags

  end

match  ':controller/:action.:format'

  root :to => 'search#search'

  mount Blogit::Engine => '/blog'

  get 'subject_tags/:tag', to: 'subjects#index', as: :subject_tag
  get 'source_tags/:tag', to: 'sources#index', as: :source_tag

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base


  require "acts-as-taggable-on"
  acts_as_taggable

  attr_accessible :subject_id, :name, :description, :purpose, :complexity, 
  :category1_id, :category2_id, :category3_id, :avgtimetolearn, :tag_list, :slug
  #tag_list added along with require at top to link with acts-as-taggable-on


  has_many :subject_modules, :inverse_of => :subject
  has_many :portfolios
  has_many :sources, through: :portfolios
  belongs_to :category1
  	delegate :cat1cod, :cat1desc, :to => :category1
  belongs_to :category2
  	delegate :cat2cod, :cat2desc, :to => :category2
  belongs_to :category3
	delegate :cat3cod, :cat3desc, :to => :category3
  has_many :contenttags, :as => :taggable
  attr_accessible :subject_modules_attributes

  has_many :portfolios, :through => :subject_modules, :inverse_of => :subject

  attr_accessible :subject_modules_attributes # not sure why I have this twice but will leave for now

  accepts_nested_attributes_for :subject_modules, :reject_if => lambda { |a| a[:smname].blank? }, :allow_destroy => true

  belongs_to :created_by, class_name: 'User' #, :inverse_of => :subjects
  belongs_to :updated_by, class_name: 'User' #, :inverse_of => :subjects

  def updater(user)
    self.updated_by_id = user.id
    self.save
  end

  def subname
    name
  end

  def srchtitle
    name
  end

  def clstype
    "Subject"
  end

  def srchtext
    description
  end

  def pagetitle
    name
  end


  validates :name,
            :presence => true,
            :uniqueness => true,

            :length => { :maximum => 50, :minimum => 3 }

    validates :description,
            :presence => true,
            
            :length => { :maximum => 300, :minimum => 3 }

    validates :purpose,
            :presence => true,
            
            :length => { :maximum => 300, :minimum => 3 }

    validates :complexity,
            :presence => true,
            :inclusion => { :in => 1..10, :message => "must be between 1 and 10" }

    validates :avgtimetolearn,
            :presence => true,
            :inclusion => { :in => 1..365, :message => "must be between 1 and 365" }   

  #def new_subject_module_attributes=(subject_modules_attributes)
  #  subject_module_attributes.each do |attributes|
  #    subject_modules.build(attributes)
  #  end
  #end

  #def existing_subject_module_attributes=(subject_modules_attributes)
  #  subject_modules.reject(&:new_record?).each do |subject_module|
  #    attributes = subject_module_attributes[subject_module.id.to_s]
  #    if attributes['_delete'] == '1'
  #      subject_modules.delete(subject_module)
  #    else
  #      subject_module.attributes = attributes
  #    end
  #  end
  #end

  private

  def save_subject_modules
    subject_modules.each do |subject_module|
      subject_module.save(false)
    end
  end



#after_update :save_subject_modules
validates_associated :subject_modules

  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?

    new_record?
  end


  include PgSearch
  multisearchable :against => [:name, :description, :purpose, :complexity]
  pg_search_scope :search_by_basic, :against => [:name, :description, :purpose, :complexity],
  :associated_against => {:subject_modules => [:smname, :smdescription, :smpurpose], :category1 => :cat1desc, :category2 => :cat2desc, :category3 => :cat3desc}


  resourcify

  #TODO:  Need to merge index page code or set jquery to refresh so that page does not load double
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  load_and_authorize_resource
  # GET /subjects
  # GET /subjects.json
  def index

    if params[:tag]
      @subjects = Subject.tagged_with(params[:tag])

    elsif params[:srchquery]
      @subjects = Subject.search_by_basic(params[:srchquery])
    else
      @subjects = Subject.all
    end

    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new
    @subject.subject_modules.build
    #@subject.build_subject_modules

    #1.times { @subject.subject_modules.build }
    @subject_modules = @subject.subject_modules
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
    @subject.subject_modules.build

    @subject_modules = @subject.subject_modules
   # 4.times {@subject_modules.build}
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = current_user.subjects.new(params[:subject])


    respond_to do |format|
      if @subject.save
        if @subject.subject_modules.count == 0
          savegeneralmodule(@subject)
        end
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def savegeneralmodule(newsub)
    @genmod = newsub.subject_modules.new

    @genmod.smname = 'General'
    @genmod.smdescription = 'Basic description of the subject'
    @genmod.order = 1
    @genmod.smpurpose = 'This is the main item related to the subject'


    @genmod.save!
  end


  # PUT /subjects/1
  # PUT /subjects/1.json
  def update

    @subject = Subject.find(params[:id])

    respond_to do |format|

      #@arrlen = params[:subject]['subject_modules_attributes'].length
      #@arrlen.times {@subject.subject_modules.build}

      if @subject.update_attributes(params[:subject])

        #if @subject.save
        if  @subject.updater current_user
          format.html { redirect_to @subject, notice: 'Subject and Module(s) successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @subject.errors, status: :unprocessable_entity }
        end

      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end

  def subject_module_fields 
  end


end

app/helpers/subjects_helper.rb
module SubjectsHelper


end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<fieldset>
  
  <div class="control-group">
        <%= f.label(:name, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:name, :class => "input-xlarge") %>
        </div>
  </div>
    <div class="control-group">
        <%= f.label(:description, :class => "control-label") %>
        <div class="controls">
          <%= f.text_area(:description, :class => "input-xlarge", :rows => 3 ) %>
        </div>
  </div>


   <div class="control-group">
        <%= f.label(:purpose, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:purpose, :class => "input-xlarge") %>
        </div>
  </div>

  <div class="field">
    <%= f.label :complexity %><br />
    <%= f.text_field :complexity %>
  </div>

  <div class="field">   
    <%= f.label :category1 %><br />
    <%= f.collection_select :category1_id, Category1.find(:all), :id, :cat1desc, :prompt => "Select a Category 1" %>
  </div>
  <div class="field" id="category2_field">
    <%= f.label :category2 %><br />
    
    <%= f.collection_select :category2_id, Category2.find(:all), :id, :cat2desc, :prompt => "Select a Category 2" %>
  </div>
  <div class="field" id="category3_field">
    <%= f.label :category3 %><br />
    
    <%= f.collection_select :category3_id, Category3.find(:all), :id, :cat3desc, :prompt => "Select a Category 3" %>
  </div>


  
  <div class="field">
    <%= f.label :avgtimetolearn %><br />
    <%= f.number_field :avgtimetolearn %>
  </div>

  <div class="field" id="new_subject_tag_field" >
      <%= f.label :tag_list,  t(:tags, scope: 'subjects') %><br />
      <%= f.text_field :tag_list %>
  </div>
</fieldset>
  <p> </p>

    <fieldset>
      <legend>Modules <%= "for #{ @subject.name }" unless @subject.name.blank? %></legend>
      <div  id="subject_modules">
        <table width="200" id="subject_modules-table" class="table table-hover table-striped" >
          <thead>
          <th>
            <div class="control-group">
            <label class="control-label">Name</label>
            </div>
          </th>
          <th>
            <div class="control-group">
              <label class="control-label">Description</label>
            </div>
          </th>
          <th>
            <div class="control-group">
              <label class="control-label">Purpose</label>
            </div>

          </th>
          <th></th>
          </thead>
          <tbody>

          <tr><td><p><%= link_to_add_fields2( "Add a Module", f, :subject_modules,:class => "btn btn-primary") %></p></td><td></td><td></td><td></td></tr>

          <%= render('subject_module_fields', :f => f) %>
          </tbody>
        </table>
        <p></p>
      </div>
    </fieldset>



<div class="modal-footer">
      <%= f.submit("Save", :class => "btn btn-primary", :title => "Save the changes to this Subject.") %>
      <%= link_to("Cancel", subjects_path, :confirm => "Are you sure you want to cancel?  Any changes will be lost.", :class => "btn btn-inverse", :title => "Cancel the changes and return to the Home page.") %>
</div>

<% end %>

app/views/subjects/_subject_module_display.html.erb
<table id="subject_modules-display-table" class="table table-hover table-striped">
  <thead>
      <th>Name</th>
      <th>Description</th>
      <th>Purpose</th>
  </thead>
  <tbody>

    <% if @subject.subject_modules.present? %>
      <% @subject.subject_modules.each do |subject_modules| %>
          <tr class="fields">
            <td><%= subject_modules.smname %></td>
            <td><%= subject_modules.smdescription %></td>
            <td><%= subject_modules.smpurpose %></td>
          </tr>
      <% end %>
    <% else %>
    <tr class="fields">
      <td colspan="3">No Modules Found</td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/subjects/_subject_module_fields.html.erb
<%= f.fields_for(:subject_modules) do |subject_modules_form| %>
<tr class="fields">
<td>


  <div class="control-group">
    <div class="controls">
      <%= subject_modules_form.text_field(:smname, :class => "input-xlarge field", :size => 35, :data => { :validation => "required validate_max_length length50", "validation-error-msg" => "A Name is required and cannot be longer than 50 characters." }) %>
    </div>
  </div>

</td>

<td>

  <div class="control-group">
    <div class="controls">
      <%= subject_modules_form.text_area(:smdescription, :class => "input-xlarge field", :rows => 3) %>
    </div>
  </div>


</td>

<td>

  <div class="control-group">
    <div class="controls">
      <%= subject_modules_form.text_area(:smpurpose, :class => "input-xlarge field", :rows => 3) %>
    </div>
  </div>
  <%= subject_modules_form.hidden_field(:_destroy, :class => "field") %>


</td>
  <% if current_page?(new_subject_path) || current_page?(edit_subject_path) %>
      <td>

        <%= link_to_remove_fields('<b class="icon-remove">x</b>'.html_safe, subject_modules_form, :title => "Delete this Module.") %>
      </td>
  <% end %>



</tr>

<% end %>

app/views/subjects/_subject_module_fields_modal.html.erb
<div id="new-subject_module-fields" class="modal fade" data-backdrop="static">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Add a Module<%= " to the #{ @subject.name } Subject" unless @subject.name.nil? %></h3>
  </div>
  <div class="modal-body">
    <fieldset>

      <div class="control-group">
        <%= f.label(:smname, :class => "control-label") %>
        <div class="controls">
          
          <%= f.text_field(:smname, :class => "input-xlarge field", :size => 35, :data => { :validation => "required validate_max_length length50", "validation-error-msg" => "A Name is required and cannot be longer than 50 characters." }) %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label(:smdescription, :class => "control-label") %>
        <div class="controls">
          <%= f.text_area(:smdescription, :class => "input-xlarge field", :rows => 3) %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label(:smpurpose, :class => "control-label") %>
        <div class="controls">
          <%= f.text_area(:smpurpose, :class => "input-xlarge field", :rows => 3) %>
        </div>
      </div>
      <%= f.hidden_field(:_destroy, :class => "field") %>
    </fieldset>
  </div>
  <div class="modal-footer">
    <button id="addButton" type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true" title="Add this subject_module to the list of subject modules that are assigned to this subject.">Add</button>
    <button id="cancelButton" type="button" class="btn btn-inverse" data-dismiss="modal" aria-hidden="true" title="Close this screen without adding the subject_module to the list.">Cancel</button>
  </div>
</div>

<script type="text/javascript">
  subject_moduleFieldsUI.init();
</script>

app/views/subjects/_subject_module_fields_old.html.erb
<div class="subject_module">
<fieldset>
	
<p>
  <%= f.label :smname, "Name" %><br />
  <%= f.text_field :smname, :size => 35 %><br />
  <%= f.label :smdescription, "Description" %><br />
  <%= f.text_area :smdescription, :rows => 3 %><br />
  <%= f.label :smpurpose, "Purpose" %><br />
  <%= f.text_area :smpurpose, :rows => 3 %><br />
  
</p>

</fieldset>
</div>
 

app/views/subjects/_subject_module_table.html.erb
<table id="subject_modules-table" class="table table-hover table-striped">
  <thead>
    <th>Name</th>
    <th>Description</th>
    <th>Purpose</th>
  <th></th>
  </thead>
  <tbody>
    <%= f.fields_for(:subject_modules) do |subject_modules_form| %>
      <tr class="fields">
        <td><%= subject_modules_form.text_field(:smname, :size => 35) %></td>
        <td><%= subject_modules_form.text_area(:smdescription, :rows => 3) %></td>
        <td><%= subject_modules_form.text_area(:smpurpose, :rows => 3) %></td>
        <% if current_page?(new_subject_path) || current_page?(edit_subject_path) %>
            <td>
              <%= link_to_remove_fields('<b class="icon-remove">x</b>'.html_safe, subject_modules_form, :title => "Delete this Module.") %>
            </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/subjects/_subjectindexgrid.html.erb
<div id="masonry-container" class="transitions-enabled infinite-scroll  clearfix">
  <% @subjects.each do |subject| %>

      <div class="boxd3 col2" >

            <h4><%= link_to subject.name, subject,:class => "gridlink" %></h4>

        <p><strong>Description</strong>: <%= truncate(subject.description, length: 100) %></p>
        <p><strong>Purpose</strong>: <%= subject.purpose %></p>

        <!--
        <p><%= subject.complexity %></p>

        <p><%= subject.category1.cat1desc %></p>
        <p><%= subject.category2.cat2desc %></p>
        <p><%= subject.category3.cat3desc %></p>
        <p><%= subject.avgtimetolearn %></p>
        -->
        <p>
        <%= link_to glyph('info-sign'), subject %>
        <%= link_to glyph(:edit), edit_subject_path(subject) %>
        <%= link_to glyph(:remove), subject, method: :delete, data: { confirm: 'Are you sure?' } %></p>


      </div>
  <% end %>
</div>

<br>

app/views/subjects/_subjectindextable.html.erb
<table class="table table-striped">
  <tr>

    <th>Name</th>
    <th>Description</th>
    <th>Purpose</th>
    <th>Complexity</th>

    <th>Category1</th>
    <th>Category2</th>
    <th>Category3</th>
    <th>Learn Time</th>
    <th></th>
  </tr>

  <% @subjects.each do |subject| %>

      <tr>

        <td width="100"><%= link_to subject.name, subject, :class => "tablelink" %></td>
        <td width="200"><%= truncate(subject.description, length: 100) %></td>
        <td><%= subject.purpose %></td>
        <td>
          <%= hidden_field "complexityval", subject.id, :value => subject.complexity %>


          <div class="progress">
            <div id="complexbarlow_<%= subject.id %>" name="complexbarlow[<%= subject.id %>]" class="bar bar-success mypopover" style="width:33%;" title="" data-content="Easy peezy" data-placement="bottom" data-toggle="popover" data-original-title="Meh"></div>
            <div id="complexbarmid_<%= subject.id %>" name="complexbarlow[<%= subject.id %>]" class="bar bar-warning mypopover" style="width:33%;" title="" data-content="Getting hot in here" data-placement="bottom" data-toggle="popover" data-original-title="Hmm"></div>
            <div id="complexbarhigh_<%= subject.id %>" name="complexbarlow[<%= subject.id %>]" class="bar bar-danger mypopover" style="width:33%;" title="" data-content="You will not succeed" data-placement="bottom" data-toggle="popover" data-original-title="Sigh"></div>
          </div>
        </td>

        <td><%= subject.category1.cat1desc %></td>
        <td><%= subject.category2.cat2desc %></td>
        <td><%= subject.category3.cat3desc %></td>
        <td><%= subject.avgtimetolearn %></td>
        <td>
        <%= link_to 'Show', subject, :class => 'btn btn-mini' %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_subject_path(subject) , :class => 'btn btn-mini' %>

        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    subject,
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
</table>
<br>

app/views/subjects/edit.html.erb
<% title 'Make changes to ' + @subject.srchtitle %>

<h1>Editing subject</h1>
<% javascript '/javascripts/dynamic_category2s' %>


<%= render 'form' %>

<%= link_to 'Show', @subject %> |

app/views/subjects/index.html.erb
<% title "Browse our Subjects" %>
<%- model_class = Subject -%>

<div class="row">
  <div class="page-header col-md-12">
    <h1><span style="border-right:1px #F5D15F solid;margin-right: 10px">Subjects </span><%= link_to 'Create One', new_subject_path, class: "btn btn-mini btn-success" %>
      <%= render partial: 'search/searchmodel', locals: {:clearpath => subjects_path} %>
    </h1>
  </div>
</div>



<div id="divgrid">
<%= render partial: 'subjectindexgrid' %>
</div>
<div id="divlist">
  <%= render partial: 'subjectindextable' %>
</div>


<br />

<p>

<div id="tag_cloud" class="tag_cloud">
  <% tag_cloud Subject.tag_counts, %w[s m l] do |tag, css_class| %>
      <%= link_to tag.name, subject_tag_path(tag.name), class: css_class %>
  <% end %>
</div>
</p>

app/views/subjects/new.html.erb
<h1>New subject</h1>
<% javascript '/javascripts/dynamic_category2s' %>

<%= render 'form' %>

app/views/subjects/show.html.erb
<%- model_class = Subject -%>
<% title 'Learn about ' + @subject.pagetitle %>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %>: <%= @subject.name %></h1>
</div>

<div class="row">
    <div class="col-md-4">

    <p>
      <b>Description:</b>
      <%= @subject.description %>
    </p>

    <p>
      <b>Purpose:</b>
      <%= @subject.purpose %>
    </p>

    <p>
      <b>Complexity:</b>
      <%= @subject.complexity %>
    </p>

    <p>
      <b>Category 1:</b>
      <%= @subject.category1.cat1desc %>
    </p>

    <p>
      <b>Category 2:</b>
      <%= @subject.category2.cat2desc %>
    </p>

    <p>
      <b>Category 3:</b>
      <%= @subject.category3.cat3desc %>
    </p>

    <p>
      <b>Average Learn Time:</b>
      <%= @subject.avgtimetolearn %>
    </p>

    <p>
      <b>Tags:</b>
      <%= raw @subject.tag_list.map{ |t| link_to t, subject_tag_path(t) }.join(' | ') %>
    </p>

      </div>
    <div class="col-md-1"></div>
    <div class="col-md-7">
      <h4>Modules</h4>
        <div id="subject_module_display">
          <%= render('subject_module_display') %>
          <p></p>
        </div>
    </div>
</div>

<br><br>

<h4>Portfolios</h4>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Desc</th>
    <th>Subject & Module</th>
    <th>Source</th>

    <th>Cost</th>

    <th>Schedule Type</th>

    <th>Start Date</th>
    <th>End Date</th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @subject.portfolios.each do |portfolio| %>
      <tr>
        <td><%= link_to portfolio.prttitle , portfolio_path(portfolio) %></td>

        <td><%= portfolio.prtdesc %></td>

        <td><%= portfolio.subject_module.subjtitle %></td>
        <td><%= portfolio.source.name %></td>


        <td><%= portfolio.cost %> <%= portfolio.currency %><br><%= portfolio.costtype.costname %></td>

        <td><%= portfolio.schedtype.schedname %></td>

        <td><%=  listdt(portfolio.startdate) %></td>
        <td><%=  listdt(portfolio.enddate) %></td>

        <td>
          <%= link_to 'Show', portfolio, :class => 'btn btn-mini' %>
         </td>
      </tr>
  <% end %>
  </tbody>
</table>


<div class="form-actions">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_subject_path(@subject), :class => 'btn' %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
            subjects_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              subject_path(@subject),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>